name: release
on:
  # deployment to docker hub only manually triggered
  workflow_dispatch:

  # for production
  release:
    types: [ created ]
env:
  IMAGE_NAME: solaceiotteam/solace-axway-agent
  VERSION: "0.0.0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Auth
        if: github.event_name == 'workflow_dispatch' && github.actor != 'ricardojosegomezulmke' && github.actor != '195858' && github.actor!= 'mynecker'
        run: |
          echo "not authorized"
          echo '::set-output name=IS_AUTHORIZED::false'
        id: auth
      - name: Cancel Workflow
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - uses: actions/checkout@v2

      - name: Set versions properties
        run:  |
          VERSION=$(<version)
          echo "VERSION=$VERSION">> $GITHUB_ENV
          echo "VERSION: $VERSION"

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install shelljs
      - name: Check Docker Version Tag
        uses: actions/github-script@v5
        with:
          script:  |
            const s = require('shelljs');
            const { VERSION, IMAGE_NAME } = process.env;
            const dhid = IMAGE_NAME+":"+ VERSION
            console.log('Looking up Docker Hub for:'+dhid);
            let code = s.exec('docker manifest inspect '+dhid).code;
            if(code===0) {
              console.log(`aborting - image already exists `+dhid);
              process.exit(1);
            } else {
              console.log(`check ok - image can get published `+dhid);
            }
      - name: Build and Deploy to Docker registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:latest
            ${{env.IMAGE_NAME}}:${{env.VERSION}}
